-- =====================================================
-- SCRIPT DE LIMPIEZA: DATOS DE PRUEBA
-- =====================================================
-- Descripción: Elimina todos los datos de prueba de la base de datos
-- IMPORTANTE: Ejecutar SOLO cuando se necesite limpiar datos de prueba
-- =====================================================

-- ⚠️ ADVERTENCIA: Este script eliminará TODOS los datos de prueba
-- ⚠️ Verificar antes de ejecutar que solo se eliminen datos de prueba

-- Verificar qué datos de prueba existen antes de eliminar
SELECT 'INVENTARIOS' AS TABLA, COUNT(*) AS CANTIDAD
FROM DOCUMENTAL_OWNER.GDOC_INVENTARIO_T 
WHERE NUM_EXPEDIENTE LIKE 'EXP-TEST-%' OR NUM_EXPEDIENTE LIKE 'TEST-%'
UNION ALL
SELECT 'SUBSERIES', COUNT(*)
FROM DOCUMENTAL_OWNER.GDOC_SUBSERIES_T 
WHERE NOM_SUBSERIE LIKE '%PRUEBA%' OR NOM_SUBSERIE LIKE '%TEST%'
UNION ALL
SELECT 'SERIES', COUNT(*)
FROM DOCUMENTAL_OWNER.GDOC_SERIES_T 
WHERE NOM_SERIES LIKE '%PRUEBA%' OR NOM_SERIES LIKE '%TEST%'
UNION ALL
SELECT 'SECCIONES', COUNT(*)
FROM DOCUMENTAL_OWNER.GDOC_SECCIONES_TP 
WHERE NOM_SECCION LIKE '%PRUEBA%' OR NOM_SECCION LIKE '%TEST%';

-- Eliminar inventarios de prueba
DELETE FROM DOCUMENTAL_OWNER.GDOC_INVENTARIO_T 
WHERE NUM_EXPEDIENTE LIKE 'EXP-TEST-%'
   OR NUM_EXPEDIENTE LIKE 'TEST-%'
   OR OBSERVACIONES LIKE '%[PRUEBA]%'
   OR OBSERVACIONES LIKE '%[TEST]%'
   OR OPERADOR = '1234567890'
   OR USU_CREACION = '1234567890';

-- Eliminar subseries de prueba
DELETE FROM DOCUMENTAL_OWNER.GDOC_SUBSERIES_T 
WHERE NOM_SUBSERIE LIKE '%PRUEBA%'
   OR NOM_SUBSERIE LIKE '%TEST%'
   OR USU_CREACION = '1234567890';

-- Eliminar series de prueba
DELETE FROM DOCUMENTAL_OWNER.GDOC_SERIES_T 
WHERE NOM_SERIES LIKE '%PRUEBA%'
   OR NOM_SERIES LIKE '%TEST%'
   OR USU_CREACION = '1234567890';

-- Eliminar secciones de prueba
DELETE FROM DOCUMENTAL_OWNER.GDOC_SECCIONES_TP 
WHERE NOM_SECCION LIKE '%PRUEBA%'
   OR NOM_SECCION LIKE '%TEST%'
   OR USU_CREACION = '1234567890';

-- Verificar eliminación
SELECT 'Inventarios restantes' AS TABLA, COUNT(*) AS CANTIDAD
FROM DOCUMENTAL_OWNER.GDOC_INVENTARIO_T 
WHERE NUM_EXPEDIENTE LIKE 'EXP-TEST-%' OR NUM_EXPEDIENTE LIKE 'TEST-%'
UNION ALL
SELECT 'Subseries restantes', COUNT(*)
FROM DOCUMENTAL_OWNER.GDOC_SUBSERIES_T 
WHERE NOM_SUBSERIE LIKE '%PRUEBA%' OR NOM_SUBSERIE LIKE '%TEST%'
UNION ALL
SELECT 'Series restantes', COUNT(*)
FROM DOCUMENTAL_OWNER.GDOC_SERIES_T 
WHERE NOM_SERIES LIKE '%PRUEBA%' OR NOM_SERIES LIKE '%TEST%'
UNION ALL
SELECT 'Secciones restantes', COUNT(*)
FROM DOCUMENTAL_OWNER.GDOC_SECCIONES_TP 
WHERE NOM_SECCION LIKE '%PRUEBA%' OR NOM_SECCION LIKE '%TEST%';

COMMIT;
