-- =====================================================
-- SCRIPT DE DATOS DE PRUEBA: CATÁLOGO DE SECCIONES DOCUMENTALES
-- =====================================================
-- Descripción: Inserta el catálogo de secciones documentales (Áreas IESS)
-- Basado en: GTI-P02-F02 - ANEXO 1
-- Tablas: GDOC_CATALOGOS_T, GDOC_CATALOGOSDET_T
-- =====================================================

-- IMPORTANTE: Ejecutar este script conectado al schema DOCUMENTAL_OWNER
-- O usar: ALTER SESSION SET CURRENT_SCHEMA = DOCUMENTAL_OWNER;

-- Configurar codificación UTF-8 para caracteres especiales
ALTER SESSION SET NLS_LANGUAGE = 'SPANISH';
ALTER SESSION SET NLS_TERRITORY = 'ECUADOR';

-- =====================================================
-- INSERT 1: Crear catálogo maestro SECCIONES_DOC
-- =====================================================
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOS_T (
    ID_CATALOGO,
    COD_CATALOGO,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO
) VALUES (
    DOCUMENTAL_OWNER.GDOC_CATALOGOS_S.NEXTVAL,
    'SECCIONES_DOC',
    'Catálogo de secciones documentales - Áreas IESS',
    'A',
    'Catálogo basado en ANEXO 1 del requerimiento funcional GTI-P02-F02',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50)
);

-- =====================================================
-- INSERT 2-N: Insertar detalles del catálogo (Áreas IESS)
-- =====================================================
-- Nota: Se usa SELECT para obtener el ID_CATALOGO dinámicamente
-- Basado en ANEXO 1 del requerimiento funcional GTI-P02-F02

-- Función auxiliar para insertar área (patrón reutilizable)
-- AI - AUDITORÍA INTERNA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'AI',
    'AUDITORÍA INTERNA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNA - COMISIÓN NACIONAL DE APELACIONES
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNA',
    'COMISIÓN NACIONAL DE APELACIONES',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CPPCP - COMISIÓN PROVINCIAL DE PRESTACIONES Y CONTROVERSIAS PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CPPCP',
    'COMISIÓN PROVINCIAL DE PRESTACIONES Y CONTROVERSIAS PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNGD - SUBDIRECCIÓN NACIONAL DE GESTIÓN DOCUMENTAL
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNGD',
    'SUBDIRECCIÓN NACIONAL DE GESTIÓN DOCUMENTAL',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DNTI - DIRECCIÓN NACIONAL DE TECNOLOGÍAS DE LA INFORMACIÓN
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DNTI',
    'DIRECCIÓN NACIONAL DE TECNOLOGÍAS DE LA INFORMACIÓN',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DG - DIRECCIÓN GENERAL
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DG',
    'DIRECCIÓN GENERAL',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- COTIEM - COMISIÓN TÉCNICA INSTITUCIONAL PARA LA EVALUACIÓN DE LOS MEDICAMENTOS
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'COTIEM',
    'COMISIÓN TÉCNICA INSTITUCIONAL PARA LA EVALUACIÓN DE LOS MEDICAMENTOS QUE NO CONSTAN EN EL CUADRO NACIONAL DE MEDICAMENTOS BÁSICOS (CNMB) VIGENTE',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CAIR - COMITÉ DE ADMINISTRACIÓN INTEGRAL DE RIESGOS
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CAIR',
    'COMITÉ DE ADMINISTRACIÓN INTEGRAL DE RIESGOS',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CAIESS - COMITÉ DE AUDITORÍA DEL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CAIESS',
    'COMITÉ DE AUDITORÍA DEL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CE - COMITÉ DE ÉTICA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CE',
    'COMITÉ DE ÉTICA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CGCSDI - COMITÉ DE GESTIÓN DE CALIDAD DE SERVICIO Y DESARROLLO INSTITUCIONAL
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CGCSDI',
    'COMITÉ DE GESTIÓN DE CALIDAD DE SERVICIO Y DESARROLLO INSTITUCIONAL',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CL - COMITÉ DE LIQUIDEZ DEL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CL',
    'COMITÉ DE LIQUIDEZ DEL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CSI - COMITÉ DE SEGURIDAD DE LA INFORMACIÓN
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CSI',
    'COMITÉ DE SEGURIDAD DE LA INFORMACIÓN',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CTIESS - COMITÉ DE TRANSPARENCIA DEL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CTIESS',
    'COMITÉ DE TRANSPARENCIA DEL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CVIRP - COMITÉ DE VALUACIÓN DE INCAPACIDADES Y DE RESPONSABILIDAD PATRONAL
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CVIRP',
    'COMITÉ DE VALUACIÓN DE INCAPACIDADES Y DE RESPONSABILIDAD PATRONAL',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CIIESS - COMITÉ INFORMÁTICO DEL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CIIESS',
    'COMITÉ INFORMÁTICO DEL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CIDBDIESS - COMITÉ INSTITUCIONAL DE BECAS DEL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CIDBDIESS',
    'COMITÉ INSTITUCIONAL DE BECAS DEL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNV - COMITÉ NACIONAL VALUADOR
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNV',
    'COMITÉ NACIONAL VALUADOR',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CPP - COMPRAS PÚBLICAS PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CPP',
    'COMPRAS PÚBLICAS PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CD-AS - CONSEJO DIRECTIVO ASEGURADOS
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CD-AS',
    'CONSEJO DIRECTIVO ASEGURADOS',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CD-EM - CONSEJO DIRECTIVO EMPLEADORES
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CD-EM',
    'CONSEJO DIRECTIVO EMPLEADORES',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNASS - COORDINACIÓN NACIONAL DE ARTICULACIÓN DEL SEGURO DE SALUD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNASS',
    'COORDINACIÓN NACIONAL DE ARTICULACIÓN DEL SEGURO DE SALUD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNAPHUM - COORDINACIÓN NACIONAL DE ATENCIÓN PRE HOSPITALARIA Y UNIDADES MÓVILES
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNAPHUM',
    'COORDINACIÓN NACIONAL DE ATENCIÓN PRE HOSPITALARIA Y UNIDADES MÓVILES',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNC - COORDINACIÓN NACIONAL DE CALIDAD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNC',
    'COORDINACIÓN NACIONAL DE CALIDAD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNCPNA - COORDINACIÓN NACIONAL DE CENTROS DE PRIMER NIVEL DE ATENCIÓN
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNCPNA',
    'COORDINACIÓN NACIONAL DE CENTROS DE PRIMER NIVEL DE ATENCIÓN',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNCE - COORDINACIÓN NACIONAL DE CENTROS ESPECIALIZADOS
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNCE',
    'COORDINACIÓN NACIONAL DE CENTROS ESPECIALIZADOS',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNCTSS - COORDINACIÓN NACIONAL DE CONTROL TÉCNICO DEL SEGURO DE SALUD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNCTSS',
    'COORDINACIÓN NACIONAL DE CONTROL TÉCNICO DEL SEGURO DE SALUD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNDM - COORDINACIÓN NACIONAL DE DISPOSITIVOS MÉDICOS
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNDM',
    'COORDINACIÓN NACIONAL DE DISPOSITIVOS MÉDICOS',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNECS - COORDINACIÓN NACIONAL DE ECONOMÍA DE LA SALUD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNECS',
    'COORDINACIÓN NACIONAL DE ECONOMÍA DE LA SALUD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNES - COORDINACIÓN NACIONAL DE EQUIPAMIENTO SANITARIO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNES',
    'COORDINACIÓN NACIONAL DE EQUIPAMIENTO SANITARIO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNESS - COORDINACIÓN NACIONAL DE ESTADÍSTICA DE SALUD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNESS',
    'COORDINACIÓN NACIONAL DE ESTADÍSTICA DE SALUD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNGRED - COORDINACIÓN NACIONAL DE GESTIÓN DEL RIESGO DE EMERGENCIAS Y DESASTRES
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNGRED',
    'COORDINACIÓN NACIONAL DE GESTIÓN DEL RIESGO DE EMERGENCIAS Y DESASTRES',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNH - COORDINACIÓN NACIONAL DE HOSPITALES
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNH',
    'COORDINACIÓN NACIONAL DE HOSPITALES',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNIM - COORDINACIÓN NACIONAL DE INFRAESTRUCTURA MÉDICA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNIM',
    'COORDINACIÓN NACIONAL DE INFRAESTRUCTURA MÉDICA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNIS - COORDINACIÓN NACIONAL DE INTELIGENCIA DE LA SALUD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNIS',
    'COORDINACIÓN NACIONAL DE INTELIGENCIA DE LA SALUD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNM - COORDINACIÓN NACIONAL DE MEDICAMENTOS
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNM',
    'COORDINACIÓN NACIONAL DE MEDICAMENTOS',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNPPS - COORDINACIÓN NACIONAL DE PROMOCIÓN Y PREVENCIÓN DE SALUD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNPPS',
    'COORDINACIÓN NACIONAL DE PROMOCIÓN Y PREVENCIÓN DE SALUD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNVESS - COORDINACIÓN NACIONAL DE VIGILANCIA EPIDEMIOLÓGICA DEL SEGURO DE SALUD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNVESS',
    'COORDINACIÓN NACIONAL DE VIGILANCIA EPIDEMIOLÓGICA DEL SEGURO DE SALUD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CNIRFSS - COORDINACIÓN NACIONAL INSTITUCIONAL DE RECUPERACIÓN DE FONDOS DEL SEGURO DE SALUD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CNIRFSS',
    'COORDINACIÓN NACIONAL INSTITUCIONAL DE RECUPERACIÓN DE FONDOS DEL SEGURO DE SALUD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DAIE - DIRECCIÓN ACTUARIAL, DE INVESTIGACIÓN Y ESTADÍSTICA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DAIE',
    'DIRECCIÓN ACTUARIAL, DE INVESTIGACIÓN Y ESTADÍSTICA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DSGRT - DIRECCIÓN DEL SEGURO GENERAL DE RIESGOS DEL TRABAJO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DSGRT',
    'DIRECCIÓN DEL SEGURO GENERAL DE RIESGOS DEL TRABAJO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DSGSIF - DIRECCIÓN DEL SEGURO GENERAL DE SALUD INDIVIDUAL Y FAMILIAR
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DSGSIF',
    'DIRECCIÓN DEL SEGURO GENERAL DE SALUD INDIVIDUAL Y FAMILIAR',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DSSC - DIRECCIÓN DEL SEGURO SOCIAL CAMPESINO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DSSC',
    'DIRECCIÓN DEL SEGURO SOCIAL CAMPESINO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DSP - DIRECCIÓN DEL SISTEMA DE PENSIONES
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DSP',
    'DIRECCIÓN DEL SISTEMA DE PENSIONES',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DNAC - DIRECCIÓN NACIONAL DE AFILIACIÓN Y COBERTURA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DNAC',
    'DIRECCIÓN NACIONAL DE AFILIACIÓN Y COBERTURA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DNCS - DIRECCIÓN NACIONAL DE COMUNICACIÓN SOCIAL
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DNCS',
    'DIRECCIÓN NACIONAL DE COMUNICACIÓN SOCIAL',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DNCRI - DIRECCIÓN NACIONAL DE COOPERACIÓN Y RELACIONES INTERNACIONALES
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DNCRI',
    'DIRECCIÓN NACIONAL DE COOPERACIÓN Y RELACIONES INTERNACIONALES',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DNFTSD - DIRECCIÓN NACIONAL DE FONDOS DE TERCEROS Y SEGURO DE DESEMPLEO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DNFTSD',
    'DIRECCIÓN NACIONAL DE FONDOS DE TERCEROS Y SEGURO DE DESEMPLEO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DNGF - DIRECCIÓN NACIONAL DE GESTIÓN FINANCIERA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DNGF',
    'DIRECCIÓN NACIONAL DE GESTIÓN FINANCIERA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DNPL - DIRECCIÓN NACIONAL DE PLANIFICACIÓN
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DNPL',
    'DIRECCIÓN NACIONAL DE PLANIFICACIÓN',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DNPR - DIRECCIÓN NACIONAL DE PROCESOS
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DNPR',
    'DIRECCIÓN NACIONAL DE PROCESOS',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DNRGC - DIRECCIÓN NACIONAL DE RECAUDACIÓN Y GESTIÓN DE CARTERA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DNRGC',
    'DIRECCIÓN NACIONAL DE RECAUDACIÓN Y GESTIÓN DE CARTERA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DNRI - DIRECCIÓN NACIONAL DE RIESGOS INSTITUCIONALES
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DNRI',
    'DIRECCIÓN NACIONAL DE RIESGOS INSTITUCIONALES',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DNSIPD - DIRECCIÓN NACIONAL DE SEGURIDAD DE LA INFORMACIÓN Y PROTECCIÓN DE DATOS
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DNSIPD',
    'DIRECCIÓN NACIONAL DE SEGURIDAD DE LA INFORMACIÓN Y PROTECCIÓN DE DATOS',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DNSC - DIRECCIÓN NACIONAL DE SERVICIOS CORPORATIVOS
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DNSC',
    'DIRECCIÓN NACIONAL DE SERVICIOS CORPORATIVOS',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DNSAC - DIRECCIÓN NACIONAL DE SERVICIOS DE ATENCIÓN AL CIUDADANO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DNSAC',
    'DIRECCIÓN NACIONAL DE SERVICIOS DE ATENCIÓN AL CIUDADANO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDG - SUBDIRECCIÓN GENERAL
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDG',
    'SUBDIRECCIÓN GENERAL',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNA - SUBDIRECCIÓN NACIONAL ADMINISTRATIVA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNA',
    'SUBDIRECCIÓN NACIONAL ADMINISTRATIVA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNACGI - SUBDIRECCIÓN NACIONAL DE AFILIACIÓN, COBERTURA Y GESTIÓN DE LA INFORMACIÓN
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNACGI',
    'SUBDIRECCIÓN NACIONAL DE AFILIACIÓN, COBERTURA Y GESTIÓN DE LA INFORMACIÓN',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNAS - SUBDIRECCIÓN NACIONAL DE ARQUITECTURA Y SOLUCIONES
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNAS',
    'SUBDIRECCIÓN NACIONAL DE ARQUITECTURA Y SOLUCIONES',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNASS - SUBDIRECCIÓN NACIONAL DE ASEGURAMIENTO DEL SEGURO DE SALUD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNASS',
    'SUBDIRECCIÓN NACIONAL DE ASEGURAMIENTO DEL SEGURO DE SALUD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNAL - SUBDIRECCIÓN NACIONAL DE ASESORÍA LEGAL
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNAL',
    'SUBDIRECCIÓN NACIONAL DE ASESORÍA LEGAL',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNCP - SUBDIRECCIÓN NACIONAL DE COMPRAS PÚBLICAS
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNCP',
    'SUBDIRECCIÓN NACIONAL DE COMPRAS PÚBLICAS',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNCPR - SUBDIRECCIÓN NACIONAL DE CONSOLIDACIÓN DE PRESUPUESTO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNCPR',
    'SUBDIRECCIÓN NACIONAL DE CONSOLIDACIÓN DE PRESUPUESTO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNC - SUBDIRECCIÓN NACIONAL DE CONTABILIDAD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNC',
    'SUBDIRECCIÓN NACIONAL DE CONTABILIDAD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNCT - SUBDIRECCIÓN NACIONAL DE CONTROL TÉCNICO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNCT',
    'SUBDIRECCIÓN NACIONAL DE CONTROL TÉCNICO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNDI - SUBDIRECCIÓN NACIONAL DE DESARROLLO INFORMÁTICO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNDI',
    'SUBDIRECCIÓN NACIONAL DE DESARROLLO INFORMÁTICO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNFT - SUBDIRECCIÓN NACIONAL DE FONDOS DE TERCEROS
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNFT',
    'SUBDIRECCIÓN NACIONAL DE FONDOS DE TERCEROS',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNGCSSS - SUBDIRECCIÓN NACIONAL DE GARANTÍA DE LA CALIDAD DE LOS SERVICIOS DEL SEGURO DE SALUD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNGCSSS',
    'SUBDIRECCIÓN NACIONAL DE GARANTÍA DE LA CALIDAD DE LOS SERVICIOS DEL SEGURO DE SALUD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNGC - SUBDIRECCIÓN NACIONAL DE GESTIÓN DE CARTERA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNGC',
    'SUBDIRECCIÓN NACIONAL DE GESTIÓN DE CARTERA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNGTH - SUBDIRECCIÓN NACIONAL DE GESTIÓN DE TALENTO HUMANO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNGTH',
    'SUBDIRECCIÓN NACIONAL DE GESTIÓN DE TALENTO HUMANO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNGCSRT - SUBDIRECCIÓN NACIONAL DE GESTIÓN Y CONTROL DEL SEGURO DE RIESGOS DEL TRABAJO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNGCSRT',
    'SUBDIRECCIÓN NACIONAL DE GESTIÓN Y CONTROL DEL SEGURO DE RIESGOS DEL TRABAJO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNGCSSC - SUBDIRECCIÓN NACIONAL DE GESTIÓN Y CONTROL DEL SEGURO SOCIAL CAMPESINO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNGCSSC',
    'SUBDIRECCIÓN NACIONAL DE GESTIÓN Y CONTROL DEL SEGURO SOCIAL CAMPESINO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNGCSP - SUBDIRECCIÓN NACIONAL DE GESTIÓN Y CONTROL DEL SISTEMA DE PENSIONES
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNGCSP',
    'SUBDIRECCIÓN NACIONAL DE GESTIÓN Y CONTROL DEL SISTEMA DE PENSIONES',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDITI - SUBDIRECCIÓN NACIONAL DE INFRAESTRUCTURA DE TECNOLOGÍAS DE LA INFORMACIÓN
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDITI',
    'SUBDIRECCIÓN NACIONAL DE INFRAESTRUCTURA DE TECNOLOGÍAS DE LA INFORMACIÓN',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNIE - SUBDIRECCIÓN NACIONAL DE INFRAESTRUCTURA Y EQUIPAMIENTO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNIE',
    'SUBDIRECCIÓN NACIONAL DE INFRAESTRUCTURA Y EQUIPAMIENTO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNP - SUBDIRECCIÓN NACIONAL DE PATROCINIO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNP',
    'SUBDIRECCIÓN NACIONAL DE PATROCINIO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNPSSSC - SUBDIRECCIÓN NACIONAL DE PRESTACIONES DE SALUD DEL SEGURO SOCIAL CAMPESINO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNPSSSC',
    'SUBDIRECCIÓN NACIONAL DE PRESTACIONES DE SALUD DEL SEGURO SOCIAL CAMPESINO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNPP - SUBDIRECCIÓN NACIONAL DE PROGRAMACIÓN Y PROYECTOS
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNPP',
    'SUBDIRECCIÓN NACIONAL DE PROGRAMACIÓN Y PROYECTOS',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNPSS - SUBDIRECCIÓN NACIONAL DE PROVISIÓN DE SERVICIOS DE SALUD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNPSS',
    'SUBDIRECCIÓN NACIONAL DE PROVISIÓN DE SERVICIOS DE SALUD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNR - SUBDIRECCIÓN NACIONAL DE RECAUDACIÓN
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNR',
    'SUBDIRECCIÓN NACIONAL DE RECAUDACIÓN',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNRF - SUBDIRECCIÓN NACIONAL DE RIESGO FINANCIERO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNRF',
    'SUBDIRECCIÓN NACIONAL DE RIESGO FINANCIERO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNSE - SUBDIRECCIÓN NACIONAL DE SEGUIMIENTO Y EVALUACIÓN
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNSE',
    'SUBDIRECCIÓN NACIONAL DE SEGUIMIENTO Y EVALUACIÓN',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNSIC - SUBDIRECCIÓN NACIONAL DE SEGURIDAD INFORMÁTICA Y CIBERSEGURIDAD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNSIC',
    'SUBDIRECCIÓN NACIONAL DE SEGURIDAD INFORMÁTICA Y CIBERSEGURIDAD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNSRFP - SUBDIRECCIÓN NACIONAL DE SUPERVISIÓN DE LA RENTABILIDAD DE LOS FONDOS PREVISIONALES
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNSRFP',
    'SUBDIRECCIÓN NACIONAL DE SUPERVISIÓN DE LA RENTABILIDAD DE LOS FONDOS PREVISIONALES',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNTP - SUBDIRECCIÓN NACIONAL DE TRANSFERENCIAS Y PAGOS
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNTP',
    'SUBDIRECCIÓN NACIONAL DE TRANSFERENCIAS Y PAGOS',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNVGIS - SUBDIRECCIÓN NACIONAL DE VIGILANCIA Y GESTIÓN DE LA INFORMACIÓN DEL SEGURO DE SALUD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNVGIS',
    'SUBDIRECCIÓN NACIONAL DE VIGILANCIA Y GESTIÓN DE LA INFORMACIÓN DEL SEGURO DE SALUD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNSD - SUBDIRECCIÓN NACIONAL DEL SEGURO DE DESEMPLEO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNSD',
    'SUBDIRECCIÓN NACIONAL DEL SEGURO DE DESEMPLEO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNFSS - SUBDIRECCIÓN NACIONAL FINANCIERA DEL SEGURO DE SALUD
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNFSS',
    'SUBDIRECCIÓN NACIONAL FINANCIERA DEL SEGURO DE SALUD',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNFSGRT - SUBDIRECCIÓN NACIONAL FINANCIERA DEL SEGURO GENERAL DE RIESGOS DEL TRABAJO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNFSGRT',
    'SUBDIRECCIÓN NACIONAL FINANCIERA DEL SEGURO GENERAL DE RIESGOS DEL TRABAJO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNFSSC - SUBDIRECCIÓN NACIONAL FINANCIERA DEL SEGURO SOCIAL CAMPESINO
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNFSSC',
    'SUBDIRECCIÓN NACIONAL FINANCIERA DEL SEGURO SOCIAL CAMPESINO',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SDNFSP - SUBDIRECCIÓN NACIONAL FINANCIERA DEL SISTEMA DE PENSIONES
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SDNFSP',
    'SUBDIRECCIÓN NACIONAL FINANCIERA DEL SISTEMA DE PENSIONES',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- PG - PROCURADURÍA GENERAL
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'PG',
    'PROCURADURÍA GENERAL',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- SPG - SUBPROCURADURÍA GENERAL
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'SPG',
    'SUBPROCURADURÍA GENERAL',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- IESS - INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'IESS',
    'INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CPAFP - COORDINACIÓN PROVINCIAL ADMINISTRATIVA FINANCIERA PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CPAFP',
    'COORDINACIÓN PROVINCIAL ADMINISTRATIVA FINANCIERA PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CPACTP - COORDINACIÓN PROVINCIAL DE AFILIACIÓN Y CONTROL TÉCNICO PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CPACTP',
    'COORDINACIÓN PROVINCIAL DE AFILIACIÓN Y CONTROL TÉCNICO PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CPAJP - COORDINACIÓN PROVINCIAL DE ASESORÍA JURÍDICA PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CPAJP',
    'COORDINACIÓN PROVINCIAL DE ASESORÍA JURÍDICA PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CPCCP - COORDINACIÓN PROVINCIAL DE CARTERA Y COACTIVA PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CPCCP',
    'COORDINACIÓN PROVINCIAL DE CARTERA Y COACTIVA PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CPPPRTFR SDP - COORDINACIÓN PROVINCIAL DE PRESTACIONES DE PENSIONES, RIESGOS DE TRABAJO, FONDOS DE TERCEROS Y SEGURO DE DESEMPLEO PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CPPPRTFRSDP',
    'COORDINACIÓN PROVINCIAL DE PRESTACIONES DE PENSIONES, RIESGOS DE TRABAJO, FONDOS DE TERCEROS Y SEGURO DE DESEMPLEO PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CPPSSP - COORDINACIÓN PROVINCIAL DE PRESTACIONES DEL SEGURO DE SALUD PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CPPSSP',
    'COORDINACIÓN PROVINCIAL DE PRESTACIONES DEL SEGURO DE SALUD PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CPSACP - COORDINACIÓN PROVINCIAL DE SERVICIOS DE ATENCIÓN AL CIUDADANO PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CPSACP',
    'COORDINACIÓN PROVINCIAL DE SERVICIOS DE ATENCIÓN AL CIUDADANO PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- CPSSCP - COORDINACIÓN PROVINCIAL DEL SEGURO SOCIAL CAMPESINO PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'CPSSCP',
    'COORDINACIÓN PROVINCIAL DEL SEGURO SOCIAL CAMPESINO PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- DPP - DIRECCIÓN PROVINCIAL PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'DPP',
    'DIRECCIÓN PROVINCIAL PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- FINP - FINANCIERO PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'FINP',
    'FINANCIERO PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- GDP - GESTIÓN DOCUMENTAL PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'GDP',
    'GESTIÓN DOCUMENTAL PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- TTHHP - TALENTO HUMANO PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'TTHHP',
    'TALENTO HUMANO PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- TIP - TECNOLOGÍA DE LA INFORMACIÓN PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'TIP',
    'TECNOLOGÍA DE LA INFORMACIÓN PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- UPCSP - UNIDAD PROVINCIAL DE COMUNICACIÓN SOCIAL PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'UPCSP',
    'UNIDAD PROVINCIAL DE COMUNICACIÓN SOCIAL PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- UPPP - UNIDAD PROVINCIAL DE PLANIFICACIÓN PICHINCHA
INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
    ID_CATALOGOSDET,
    COD_CATALOGOSDET,
    DESCRIPCION,
    ESTADO,
    OBSERVACION,
    USU_CREACION,
    FEC_CREACION,
    IP_EQUIPO,
    ID_CATALOGO
) 
SELECT 
    DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
    'UPPP',
    'UNIDAD PROVINCIAL DE PLANIFICACIÓN PICHINCHA',
    'A',
    'Sección documental - Área IESS',
    'SYSTEM',
    SYSDATE,
    SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
    ID_CATALOGO
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- =====================================================
-- NOTA: Áreas Adicionales
-- =====================================================
-- Este script incluye las áreas principales del ANEXO 1.
-- Si necesitas agregar más áreas del ANEXO 1, puedes copiar
-- el patrón de INSERT anterior y agregar nuevas áreas.
-- 
-- Formato para agregar nuevas áreas:
-- INSERT INTO DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T (
--     ID_CATALOGOSDET,
--     COD_CATALOGOSDET,
--     DESCRIPCION,
--     ESTADO,
--     OBSERVACION,
--     USU_CREACION,
--     FEC_CREACION,
--     IP_EQUIPO,
--     ID_CATALOGO
-- ) 
-- SELECT 
--     DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_S.NEXTVAL,
--     'SIGLA',
--     'NOMBRE COMPLETO DEL ÁREA',
--     'A',
--     'Sección documental - Área IESS',
--     'SYSTEM',
--     SYSDATE,
--     SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 50),
--     ID_CATALOGO
-- FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T
-- WHERE COD_CATALOGO = 'SECCIONES_DOC';

-- =====================================================
-- Verificar inserción
-- =====================================================

-- Configurar formato de salida para mejor visualización
SET PAGESIZE 1000
SET LINESIZE 200
SET FEEDBACK ON

PROMPT =====================================================
PROMPT VERIFICACIÓN DE INSERCIÓN - CATÁLOGO SECCIONES_DOC
PROMPT =====================================================
PROMPT 

-- Verificar catálogo maestro y total de detalles
PROMPT 1. RESUMEN DEL CATÁLOGO:
SELECT 
    C.COD_CATALOGO,
    C.DESCRIPCION AS CATALOGO,
    COUNT(CD.ID_CATALOGOSDET) AS TOTAL_DETALLES
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T C
LEFT JOIN DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T CD ON C.ID_CATALOGO = CD.ID_CATALOGO
WHERE C.COD_CATALOGO = 'SECCIONES_DOC'
GROUP BY C.COD_CATALOGO, C.DESCRIPCION;

PROMPT 
PROMPT 2. LISTADO DE TODAS LAS ÁREAS INSERTADAS (primeras 50):
SELECT 
    ROWNUM AS NUM,
    CD.COD_CATALOGOSDET,
    CD.DESCRIPCION
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T CD
JOIN DOCUMENTAL_OWNER.GDOC_CATALOGOS_T C ON CD.ID_CATALOGO = C.ID_CATALOGO
WHERE C.COD_CATALOGO = 'SECCIONES_DOC'
ORDER BY CD.COD_CATALOGOSDET
FETCH FIRST 50 ROWS ONLY;

PROMPT 
PROMPT 3. TOTAL DE ÁREAS INSERTADAS:
SELECT 
    COUNT(*) AS TOTAL_AREAS
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T CD
JOIN DOCUMENTAL_OWNER.GDOC_CATALOGOS_T C ON CD.ID_CATALOGO = C.ID_CATALOGO
WHERE C.COD_CATALOGO = 'SECCIONES_DOC';

PROMPT 
PROMPT =====================================================
PROMPT VERIFICACIÓN COMPLETADA
PROMPT =====================================================

COMMIT;
