-- =====================================================
-- SCRIPT DE VERIFICACIÓN: CATÁLOGO DE SECCIONES DOCUMENTALES
-- =====================================================
-- Descripción: Script para verificar la inserción del catálogo
-- Uso: Ejecutar en Toad o SQL Developer para verificar datos
-- =====================================================

-- Configurar formato de salida
SET PAGESIZE 1000
SET LINESIZE 200
SET FEEDBACK ON
SET NUMWIDTH 10

PROMPT =====================================================
PROMPT VERIFICACIÓN DE CATÁLOGO: SECCIONES_DOC
PROMPT =====================================================
PROMPT 

-- 1. Verificar catálogo maestro y total de detalles
PROMPT 1. RESUMEN DEL CATÁLOGO:
PROMPT 

SELECT 
    C.COD_CATALOGO,
    C.DESCRIPCION AS CATALOGO,
    COUNT(CD.ID_CATALOGOSDET) AS TOTAL_DETALLES
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOS_T C
LEFT JOIN DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T CD ON C.ID_CATALOGO = CD.ID_CATALOGO
WHERE C.COD_CATALOGO = 'SECCIONES_DOC'
GROUP BY C.COD_CATALOGO, C.DESCRIPCION;

PROMPT 
PROMPT 2. TOTAL DE ÁREAS INSERTADAS:
PROMPT 

SELECT 
    COUNT(*) AS TOTAL_AREAS
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T CD
JOIN DOCUMENTAL_OWNER.GDOC_CATALOGOS_T C ON CD.ID_CATALOGO = C.ID_CATALOGO
WHERE C.COD_CATALOGO = 'SECCIONES_DOC';

PROMPT 
PROMPT 3. LISTADO COMPLETO DE ÁREAS (ordenadas por código):
PROMPT 

SELECT 
    ROWNUM AS NUM,
    CD.COD_CATALOGOSDET,
    CD.DESCRIPCION
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T CD
JOIN DOCUMENTAL_OWNER.GDOC_CATALOGOS_T C ON CD.ID_CATALOGO = C.ID_CATALOGO
WHERE C.COD_CATALOGO = 'SECCIONES_DOC'
ORDER BY CD.COD_CATALOGOSDET;

PROMPT 
PROMPT 4. PRIMERAS 20 ÁREAS (ejemplo):
PROMPT 

SELECT 
    ROWNUM AS NUM,
    CD.COD_CATALOGOSDET,
    CD.DESCRIPCION
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T CD
JOIN DOCUMENTAL_OWNER.GDOC_CATALOGOS_T C ON CD.ID_CATALOGO = C.ID_CATALOGO
WHERE C.COD_CATALOGO = 'SECCIONES_DOC'
ORDER BY CD.COD_CATALOGOSDET
FETCH FIRST 20 ROWS ONLY;

PROMPT 
PROMPT 5. VERIFICAR ESTADO DE LAS ÁREAS:
PROMPT 

SELECT 
    CD.ESTADO,
    COUNT(*) AS CANTIDAD
FROM DOCUMENTAL_OWNER.GDOC_CATALOGOSDET_T CD
JOIN DOCUMENTAL_OWNER.GDOC_CATALOGOS_T C ON CD.ID_CATALOGO = C.ID_CATALOGO
WHERE C.COD_CATALOGO = 'SECCIONES_DOC'
GROUP BY CD.ESTADO;

PROMPT 
PROMPT =====================================================
PROMPT VERIFICACIÓN COMPLETADA
PROMPT =====================================================
